/*
 * This header is generated by sopc2dts version rel_14.0_RC3-19-g5528511 on Wed Mar 25 23:06:48 CST 2015
 * Sopc2dts is written by Walter Goossens <waltergoossens@home.nl>
 * in cooperation with the nios2 community <nios2-dev@lists.rocketboards.org>
 */
#ifndef CUSTOM_FPGA_H_
#define CUSTOM_FPGA_H_

/* generated from DE2_70_SOPC.sopcinfo */

/* Dumping slaves of cpu.data_master*/

/* cpu.jtag_debug_module is a altera_nios2_qsys */
#define CONFIG_SYS_CLK_FREQ	100000000
#define CONFIG_SYS_DCACHE_SIZE	2048
#define CONFIG_SYS_DCACHELINE_SIZE	32
#define CONFIG_SYS_ICACHELINE_SIZE	32
#define CONFIG_SYS_EXCEPTION_ADDR	0x02000020
#define CONFIG_SYS_ICACHE_SIZE	4096
#define CONFIG_SYS_RESET_ADDR	0x04800000
#define IO_REGION_BASE	0xE0000000

/* sdram_u1.s1 is a altera_avalon_new_sdram_controller */
#define CONFIG_SYS_SDRAM_BASE	0x2000000
#define CONFIG_SYS_SDRAM_SIZE	0x2000000

/* sysid.control_slave is a altera_avalon_sysid_qsys */
#define CONFIG_SYS_SYSID_BASE	0x850020a0

/* uart.s1 is a altera_avalon_uart */
#define CONFIG_SYS_UART_BAUD	115200
#define CONFIG_SYS_UART_BASE	0x85002040
#define CONFIG_SYS_UART_FREQ	100000000

/* pll.s1 is a altera_avalon_pll */
#define PLL_BASE	0x85002060

/* timer.s1 is a altera_avalon_timer */
#define CONFIG_SYS_TIMER_IRQ	2
#define CONFIG_SYS_TIMER_FREQ	100000000
#define CONFIG_SYS_TIMER_BASE	0x85002080

/* timer_stamp.s1 is a altera_avalon_timer */
//#define CONFIG_SYS_TIMER_IRQ	3
//#define CONFIG_SYS_TIMER_FREQ	100000000
//#define CONFIG_SYS_TIMER_BASE	0x85002000

/* petri_dma_0.petri_slave is a petri_dma */
#define PETRI_DMA_0_BASE	0x85000000

/* DM9000A.s1 is a DM9000A_IF */
#define DM9000A_BASE	0x850020a8
#define DM9000A_IRQ	1

/* cfi_flash.uas is a altera_generic_tristate_controller */
#define CFI_FLASH_BASE	0x84800000

#endif	//CUSTOM_FPGA_H_
